package co.com.PruebaWS.entidades;


import java.math.BigDecimal;

/**
 * Factura generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     private Integer cantidad_stock;     
     private BigDecimal precio_unidad;
     private String tipo;
     private Integer estado;

    public Producto() {
    }

    public Producto(String descripcion, Integer cantidad_stock, BigDecimal precio_unidad, String tipo, Integer estado) {
       this.descripcion = descripcion;
       this.cantidad_stock = cantidad_stock;
       this.precio_unidad = precio_unidad;
       this.tipo = tipo;
       this.estado = estado;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Integer getCantidad_stock() {
        return cantidad_stock;
    }

    public void setCantidad_stock(Integer cantidad_stock) {
        this.cantidad_stock = cantidad_stock;
    }

    public BigDecimal getPrecio_unidad() {
        return precio_unidad;
    }

    public void setPrecio_unidad(BigDecimal precio_unidad) {
        this.precio_unidad = precio_unidad;
    }

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public Integer getEstado() {
        return estado;
    }

    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    
}


